function idx = GetVisibleForcPart(rho, Hc, Hu, maxHc, maxHu, options)
    minHc = 0.003;
    if nargin <= 5
        options = '';
    elseif isnumeric(options)
        minHc = options; 
        options = '';
    end
    if strcmpi(options, 'cropcorner')
        idx = logical(~isnan(rho) ...
                    & Hc-minHc>0 ...
                    & Hc-minHc>-Hu ...
                    & Hc<maxHc-minHc ...
                    & abs(Hu)<maxHu);
    elseif strcmpi(options, 'keepfirstpoint')
        idx = logical(~isnan(rho) ...
                    & Hc+maxHc*0.01>=0 ...
                    & Hc<maxHc-minHc ...
                    & abs(Hu)<maxHu);
    else
        idx = logical(~isnan(rho) ...
                    & Hc-minHc>0 ...
                    & Hc<maxHc-minHc ...
                    & abs(Hu)<maxHu);
    end
end